// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.donation.eoy.version.viewed", 5);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1733082934);
user_pref("browser.search.region", "TN");
user_pref("calendar.caldav.googleResync", 1733082933);
user_pref("calendar.list.sortOrder", "63ddedb8-4db8-4aa8-a974-5c7ac2616529");
user_pref("calendar.registry.63ddedb8-4db8-4aa8-a974-5c7ac2616529.calendar-main-default", true);
user_pref("calendar.registry.63ddedb8-4db8-4aa8-a974-5c7ac2616529.calendar-main-in-composite", true);
user_pref("calendar.registry.63ddedb8-4db8-4aa8-a974-5c7ac2616529.disabled", true);
user_pref("calendar.registry.63ddedb8-4db8-4aa8-a974-5c7ac2616529.name", "Home");
user_pref("calendar.registry.63ddedb8-4db8-4aa8-a974-5c7ac2616529.type", "storage");
user_pref("calendar.registry.63ddedb8-4db8-4aa8-a974-5c7ac2616529.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Africa/Tunis");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1733082942529");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1733083050);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20241009170210");
user_pref("extensions.lastAppVersion", "115.16.0");
user_pref("extensions.lastPlatformVersion", "115.16.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"30e995b7-2a54-4faa-9a5f-08b8d26b4e75\",\"google@search.mozilla.org\":\"809a0626-1cf0-462f-bbb5-c4df859062a0\",\"ddg@search.mozilla.org\":\"bbe337fb-ab6b-437e-abe3-87a3e3455312\",\"amazondotcom@search.mozilla.org\":\"4ff186b0-f139-4012-86f0-3691ff92ae33\",\"wikipedia@search.mozilla.org\":\"de42da16-625a-4092-adc1-56caaac0e0cf\",\"bing@search.mozilla.org\":\"ff0c93ab-6401-449f-9df3-86ee1a0bb25c\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "c27b7b1a-8f44-43e6-9b48-cca97b29a0f");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.16.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("toolkit.startup.last_success", 1733083045);
user_pref("toolkit.telemetry.cachedClientID", "b9f7e642-df7c-4b23-af3c-c3ea9da85a73");
user_pref("toolkit.telemetry.previousBuildID", "20241009170210");
